services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gitdata-postgres
    environment:
      POSTGRES_DB: overlay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/postgresql-schema-complete.sql:/docker-entrypoint-initdb.d/01-complete-schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d overlay"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gitdata-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gitdata-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - gitdata-network

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitdata-app
    environment:
      NODE_ENV: development
      PORT: 8788
      BRC31_ENABLED: "false"

      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: overlay
      DB_USER: postgres
      DB_PASSWORD: password
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: overlay
      PG_USER: postgres
      PG_PASSWORD: password

      # Redis Configuration
      REDIS_URL: redis://redis:6379

      # Application Configuration
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8788

      # Security
      USE_REDIS_BUNDLES: "true"

      # Headers file for SPV (optional)
      HEADERS_FILE: /app/data/headers/headers.json
    ports:
      - "8788:8788"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8788/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - gitdata-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gitdata-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gitdata.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gitdata-network
    profiles:
      - admin

  # Optional: Redis Commander for cache management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: gitdata-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - gitdata-network
    profiles:
      - admin

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_data:
    driver: local
  app_logs:
    driver: local
  pgadmin_data:
    driver: local

# Network for service communication
networks:
  gitdata-network:
    driver: bridge
